name: tests-auth

on:
  push:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies and Run Tests
        run: |
          npm install
          npm run test:ci

